DBT_FUNDAMENTALS:
  outputs:
    dev:
      account: flrxlzm-aw92699 
      database: raw
      password: Tulsi@25
      role: accountadmin
      schema: ANALYTICS
      threads: 1
      type: snowflake
      user: Tulsi25
      warehouse: compute_wh
  target: dev
DBT_PYTHON_MODEL:
  outputs:
    dev:
      account: waqcbbe-dl27405
      database: sleekmart_oms
      password: Tulsi@25
      role: accountadmin
      schema: L3_CONSUMTIONS
      threads: 1
      type: snowflake
      user: Tulsi25
      warehouse: compute_wh
  target: dev
