name: DBT Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Set Environment Variables
      - name: Set Environment Variables
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/.github/dbt_profiles
        run: |
          echo "DBT_PROFILES_DIR is set to $DBT_PROFILES_DIR"

      # Install DBT
      - name: Install DBT
        run: |
          python -m venv dbt-env
          source dbt-env/bin/activate
          pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      # Run DBT commands
      - name: Run DBT Models
        run: |
          source dbt-env/bin/activate
          echo "Running DBT commands"
          dbt deps
          dbt run
          dbt test
