name: DBT Workflow

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Match the Python version you use locally

    # Install DBT and adapter
    - name: Install DBT
      run: |
        python -m venv dbt-env
        source dbt-env/bin/activate
        pip install --upgrade pip
        pip install dbt-core dbt-snowflake  # Use your adapter (e.g., dbt-snowflake)

    # Set environment variables (for profiles location)
    - name: Set Environment Variables
      env:
        DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}  # Path to your profiles directory

    # Verify DBT_PROFILES_DIR environment variable is set (debugging)
    - name: Debug DBT_PROFILES_DIR
      run: echo "DBT_PROFILES_DIR is set to: $DBT_PROFILES_DIR" 

    # Run DBT commands
    - name: Run DBT Models
      run: |
        source dbt-env/bin/activate
        dbt deps  # Install dependencies
        dbt run   # Run models
        dbt test  # Test models

    # Upload logs as artifacts (optional)
    - name: Upload Logs
      uses: actions/upload-artifact@v3
      with:
        name: dbt-logs
        path: logs/  # Ensure 'logs/' directory exists in your project
